spring.application.name=medecin-service

server.port=8090

spring.kafka.bootstrap-servers=localhost:9092

spring.datasource.url=jdbc:h2:mem:medecinDB 
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true